version: "3.9"

x-rails-base: &rails-base
  build: .
  volumes:
    - .:/myapp
  environment:
    RAILS_ENV: development
    DB_HOST: db
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_DATABASE: oauth_client
    # OAUTH_HOST: http://idp.myapp.local
    OAUTH_HOST: http://host.docker.internal:3000
    BACKEND_OAUTH_HOST: http://host.docker.internal:3000
    OAUTH_CLIENT_ID: web-frontend-app-client-id
    OAUTH_CLIENT_SECRET: web-frontend-app-client-secret
    # KAFKA_BROKERS: kafka-idp:9092
    KAFKA_BROKERS: host.docker.internal:9092
  depends_on:
      - db

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    <<: *rails-base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3001"
    ports:
      - "3001:3001"

  kafka-consumer:
    <<: *rails-base
    command: ["bundle", "exec", "rake", "kafka:consume"]

volumes:
  db-data:

# Useful Commands
# docker-compose run web bundle exec rake db:drop db:create db:migrate db:seed
# docker-compose run web bundle exec rails c